services:
  - type: web
    name: agroanalytics-api
    env: python
    buildCommand: cd backend && pip install --no-cache-dir -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    
    plan: free
    numInstances: 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DATABASE_URL
        scope: runtime
        value: postgresql://postgres.dhgqfdrjuxrlabopqfvo:O6mYavjmmK6LddDY@aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
      
      - key: SECRET_KEY
        scope: runtime
        value: cYZnXUdqrR-jACf5Y4892w70vhbSuh5ZVfTTuLuSf5I
      
      - key: ALGORITHM
        value: HS256
      
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      
      - key: PYTHONUNBUFFERED
        value: "1"
      
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    
    healthCheckPath: /
    healthCheckInterval: 60
    buildTimeout: 900
    startTimeout: 60

previewsEnabled: false